debug: 
	gcc -g evac.c -o evac.exe
	./evac.exe
evac:
	gcc evac.c -o evac.exe
	./evac.exe
evac-test: 
	gcc evac.c -o evac.exe
	./testmain.tcl ./evac.exe
qsort:
	gcc qsort_template.c -o qsort.exe
	./qsort.exe
clean: 
	@rm *.exe
	@clear