debug: 
	gcc -g physics.c -o physics.exe
	./physics.exe
physics:
	gcc physics.c -o physics.exe
	./physics.exe
physics-test: 
	gcc physics.c -o physics.exe
	./testmain.tcl ./physics.exe
qsort:
	gcc qsort_template.c -o qsort.exe
	./qsort.exe
clean: 
	@rm *.exe
	@clear